# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-aRqwk8hoS-CFHScTQF75XJjCK-5d8X5
"""

from transformers import pipeline

classifier = pipeline("sentiment-analysis",
                      "blanchefort/rubert-base-cased-sentiment")

classifier("Я обожаю инженерию машинного обучения!")